### ISSUE TITLE
`sha512-gen` command doesn't generate sha512

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [uclahs-cds/public-tool-PipeVal#28]
It looks like PipeVal `sha512-gen` doesn't work properly. See /hot/pipeline/development/slurm/call-sSNV/unreleased/maotian-update-docker-container/output/call-sSNV-2.1.1/A-mini/SomaticSniper-1.0.5.0/output/somaticsniper_A-mini_hc.vcf.gz
```
sha512-generated for somaticsniper_A-mini_hc.vcf.gz
Input: somaticsniper_A-mini_hc.vcf.gz is valid sha512-gen
ee48aad8c385c6a69c
```

_Originally posted by @tyamaguchi-ucla in https://github.com/uclahs-cds/pipeline-call-sSNV/pull/52#r755585227_

**Comment by tyamaguchi-ucla** [comment]
Output should be `checksum  file_name` (two white spaces between the values)

**Comment by aybeshlikyan** [comment]
Should there be a newline at the end? @tyamaguchi-ucla

**Comment by tyamaguchi-ucla** [comment]
> Should there be a newline at the end? @tyamaguchi-ucla

I think so!
