### ISSUE TITLE
Release 3.0.0(-rc.1)?

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [uclahs-cds/public-tool-PipeVal#43]
@aybeshlikyan we've updated PipeVal quite a bit and I think it's ready for a new release (esp, accepting multiple files would help simplify the NF pipeline log dir structure) unless I miss something. The version should be `2.2.0` as it's backward compatible with the previous release if I'm not mistaken. Maybe we want to test it out with align-RAN if you haven't?

**Comment by aybeshlikyan** [comment]
Yes I think it's almost ready for a new release too! I'm wrapping up #41 too then I'll test with align-RNA.

**Comment by tyamaguchi-ucla** [comment]
> The version should be `2.2.0` as it's backward compatible with the previous release if I'm not mistaken.

Oops, the version should be `3.0.0` or `3.0.0-rc.1` because we turned this repo into a python package and syntax changed.
