### ISSUE TITLE
Empty BAM check

### ISSUE THREAD

**Issue by yashpatel6** [uclahs-cds/public-tool-PipeVal#47]
With the current `samtools quickcheck`, properly formatted empty BAM files pass the validation. We want to add a check to catch these empty BAMs and an option/flag for the tool to enable/disable this check

**Comment by tyamaguchi-ucla** [comment]
A-null (a BAM with a header but no reads) is available here for now - `/hot/resource/SMC-HET/normal/bams/A-null`
