### ISSUE TITLE
Instructions for adding/updating as submodule

### ISSUE THREAD

**Issue by madisonjordan** [uclahs-cds/public-tool-PipeVal#59]
I was wondering if we could add this to the readme or wiki or something? I have to look it up every time so I thought it might be more convenient to have it written out. Either that we add it to Nextflow instructions somewhere.

### Add submodule

add submodule to desired pipeline directory:
```
git submodule add git@github.com:uclahs-cds/public-tool-PipeVal.git /path/pipeline/external/PipeVal
```

### Checkout specific release

enter created submodule directory:
```
cd /path/pipeline/external/PipeVal
```

fetch recent changes to PipeVal:
```
git fetch
```

checkout specific tag and create new (local) branch from it:
```
git checkout tags/v3.0.0 -b v3.0.0
```

**Comment by yashpatel6** [comment]
PipeVal isn't run as a submodule in any pipelines; it's run through the Docker container corresponding to a specific version of PipeVal. The submodule in pipelines is for the actual process that uses the Docker, not directly related to the PipeVal repo.

For documentation for pipelines, we do have some [here](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/How+to+run+a+nextflow+pipeline) but it can be updated with with more details if necessary.

**Comment by madisonjordan** [comment]
Oh well I've been doing it wrong then.

**Comment by yashpatel6** [comment]
Once publicly released, other users *may* end up using it as you described but at least internally, we're not doing it that way. Eventually, we do want to explicitly document the standards we use in Nextflow pipelines but we just haven't gotten around to it/standardizations are still on-going...
