### ISSUE TITLE
Ubuntu 20.04 update Dockerfile fix

### ISSUE THREAD

**Issue by yashpatel6** [uclahs-cds/public-tool-PipeVal#61]
Fix Dockerfile to successfully build with the recently updated Ubuntu 20.04 version. There are certain issues with gcc and proper dependencies/libraries for building HTSlib

**Comment by madisonjordan** [comment]
This is the manifest for the version in the `dev` tag from 2 months ago appears to be located [here](https://git.launchpad.net/cloud-images/+oci/ubuntu-base/tree/?h=refs/tags/dist-focal-amd64-20221019&id=7f6cfb71524baae0a1019f2c7b2530dff2d40c6e). 
I checked it against the `dev` image using `apt list` and the versions and dependencies appear to match.  
The  tag appears to be `dist-focal-amd64-20221019` which is listed as `focal-20221019`
on dockerhub. eg.) `docker pull ubuntu:focal-20221019`

**Comment by yashpatel6** [comment]
I did some testing and it looks like the issue actually comes from python `3.10` -> `3.11`; updating the conda create statement to install python3.10 resolves the issue. For some reason, python3.11 fails to build `pysam` (both pysam `0.19.0` and `0.20.0` fail to build with python3.11).
